-- Расширение схемы: справочник типов партнёров и поля карточки партнёра.

CREATE TABLE IF NOT EXISTS partner_types (
    partner_type_id INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name       VARCHAR(20) NOT NULL UNIQUE
);

INSERT INTO partner_types (type_name) VALUES
    ('ООО'),
    ('ЗАО'),
    ('ОАО'),
    ('ИП'),
    ('ПАО')
ON CONFLICT (type_name) DO NOTHING;

ALTER TABLE partners
    ADD COLUMN IF NOT EXISTS partner_type_id INT;

ALTER TABLE partners
    ADD COLUMN IF NOT EXISTS address VARCHAR(255);

ALTER TABLE partners
    ADD COLUMN IF NOT EXISTS director VARCHAR(255);

ALTER TABLE partners
    ADD CONSTRAINT fk_partners_partner_type
        FOREIGN KEY (partner_type_id)
        REFERENCES partner_types (partner_type_id)
        ON DELETE RESTRICT;