-- =========================================================
-- Schema for Educational Practice
-- PostgreSQL
-- =========================================================

DROP TABLE IF EXISTS delivery_items;
DROP TABLE IF EXISTS deliveries;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS partners;

-- =========================================================
-- partners — справочник партнёров
-- =========================================================
CREATE TABLE partners (
    partner_id    INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name  VARCHAR(255) NOT NULL,
    inn           VARCHAR(12)  UNIQUE,  -- ИНН: 10 цифр у юрлиц, 12 у ИП; nullable для служебных записей
    contact_email VARCHAR(255) UNIQUE,
    phone         VARCHAR(30),
    rating        NUMERIC(2,1)
);

-- =========================================================
-- products — справочник товаров
-- =========================================================
CREATE TABLE products (
    product_id   INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL UNIQUE
);

-- =========================================================
-- deliveries — шапки отгрузок (накладные)
-- =========================================================
CREATE TABLE deliveries (
    delivery_id   INT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id    INT  NOT NULL,
    delivery_date DATE NOT NULL,
    CONSTRAINT fk_deliveries_partner
        FOREIGN KEY (partner_id)
        REFERENCES partners (partner_id)
        ON DELETE RESTRICT
);

-- =========================================================
-- delivery_items — позиции отгрузок
-- =========================================================
CREATE TABLE delivery_items (
    delivery_item_id INT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id      INT           NOT NULL,
    product_id       INT           NOT NULL,
    quantity         INT           NOT NULL CHECK (quantity > 0),
    total_amount     NUMERIC(12,2) NOT NULL CHECK (total_amount >= 0),
    CONSTRAINT fk_delivery_items_delivery
        FOREIGN KEY (delivery_id)
        REFERENCES deliveries (delivery_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_delivery_items_product
        FOREIGN KEY (product_id)
        REFERENCES products (product_id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_delivery_items_delivery_product
        UNIQUE (delivery_id, product_id)
);